require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PasswordResetsController do

  def mock_password_reset(stubs={})
    @mock_password_reset ||= mock_model(PasswordReset, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all password_resets as @password_resets" do
      PasswordReset.stub(:all) { [mock_password_reset] }
      get :index
      assigns(:password_resets).should eq([mock_password_reset])
    end
  end

  describe "GET show" do
    it "assigns the requested password_reset as @password_reset" do
      PasswordReset.stub(:find).with("37") { mock_password_reset }
      get :show, :id => "37"
      assigns(:password_reset).should be(mock_password_reset)
    end
  end

  describe "GET new" do
    it "assigns a new password_reset as @password_reset" do
      PasswordReset.stub(:new) { mock_password_reset }
      get :new
      assigns(:password_reset).should be(mock_password_reset)
    end
  end

  describe "GET edit" do
    it "assigns the requested password_reset as @password_reset" do
      PasswordReset.stub(:find).with("37") { mock_password_reset }
      get :edit, :id => "37"
      assigns(:password_reset).should be(mock_password_reset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created password_reset as @password_reset" do
        PasswordReset.stub(:new).with({'these' => 'params'}) { mock_password_reset(:save => true) }
        post :create, :password_reset => {'these' => 'params'}
        assigns(:password_reset).should be(mock_password_reset)
      end

      it "redirects to the created password_reset" do
        PasswordReset.stub(:new) { mock_password_reset(:save => true) }
        post :create, :password_reset => {}
        response.should redirect_to(password_reset_url(mock_password_reset))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved password_reset as @password_reset" do
        PasswordReset.stub(:new).with({'these' => 'params'}) { mock_password_reset(:save => false) }
        post :create, :password_reset => {'these' => 'params'}
        assigns(:password_reset).should be(mock_password_reset)
      end

      it "re-renders the 'new' template" do
        PasswordReset.stub(:new) { mock_password_reset(:save => false) }
        post :create, :password_reset => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested password_reset" do
        PasswordReset.stub(:find).with("37") { mock_password_reset }
        mock_password_reset.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :password_reset => {'these' => 'params'}
      end

      it "assigns the requested password_reset as @password_reset" do
        PasswordReset.stub(:find) { mock_password_reset(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:password_reset).should be(mock_password_reset)
      end

      it "redirects to the password_reset" do
        PasswordReset.stub(:find) { mock_password_reset(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(password_reset_url(mock_password_reset))
      end
    end

    describe "with invalid params" do
      it "assigns the password_reset as @password_reset" do
        PasswordReset.stub(:find) { mock_password_reset(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:password_reset).should be(mock_password_reset)
      end

      it "re-renders the 'edit' template" do
        PasswordReset.stub(:find) { mock_password_reset(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested password_reset" do
      PasswordReset.stub(:find).with("37") { mock_password_reset }
      mock_password_reset.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the password_resets list" do
      PasswordReset.stub(:find) { mock_password_reset }
      delete :destroy, :id => "1"
      response.should redirect_to(password_resets_url)
    end
  end

end
